{{- if and .Values.sequencer.enabled .Values.sequencer.nats.embedded }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdk-erigon.fullname" . }}-sequencer
  labels:
    {{- include "cdk-erigon.labels" . | nindent 4 }}
    component: sequencer
data:
  {{- if .Values.sequencer.nats.embedded }}
  nats.conf: |
    port: 4222
    server_name: {{ include "cdk-erigon.fullname" . }}-sequencer

    jetstream {
      store_dir: "/data/nats"
      max_memory_store: {{ printf "%.0f" .Values.sequencer.nats.maxMemoryStore }}
      max_file_store: {{ printf "%.0f" .Values.sequencer.nats.maxFileStore }}
    }

    max_payload: {{ printf "%.0f" .Values.sequencer.nats.maxPayload }}
    max_pending: {{ printf "%.0f" .Values.sequencer.nats.maxPending }}
  {{- end }}
{{- end }}
