{{- if and .Values.l1Proxy.enabled .Values.l1Proxy.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cdk-erigon.fullname" . }}-l1-proxy-cache
  labels:
    {{- include "cdk-erigon.labels" . | nindent 4 }}
    app.kubernetes.io/component: l1-proxy
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.l1Proxy.persistence.storageClass }}
  storageClassName: {{ .Values.l1Proxy.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.l1Proxy.persistence.size }}
{{- end }}
