// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: datastream_service.proto

package datastream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataStreamServiceClient is the client API for DataStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataStreamServiceClient interface {
	// GetTransactionStream returns a continuous stream of transactions as they're processed
	GetTransactionStream(ctx context.Context, in *TransactionStreamRequest, opts ...grpc.CallOption) (DataStreamService_GetTransactionStreamClient, error)
	// GetStreamInfo returns information about the current datastream
	GetStreamInfo(ctx context.Context, in *StreamInfoRequest, opts ...grpc.CallOption) (*StreamInfoResponse, error)
}

type dataStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataStreamServiceClient(cc grpc.ClientConnInterface) DataStreamServiceClient {
	return &dataStreamServiceClient{cc}
}

func (c *dataStreamServiceClient) GetTransactionStream(ctx context.Context, in *TransactionStreamRequest, opts ...grpc.CallOption) (DataStreamService_GetTransactionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataStreamService_ServiceDesc.Streams[0], "/datastream.service.v1.DataStreamService/GetTransactionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataStreamServiceGetTransactionStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataStreamService_GetTransactionStreamClient interface {
	Recv() (*TransactionResponse, error)
	grpc.ClientStream
}

type dataStreamServiceGetTransactionStreamClient struct {
	grpc.ClientStream
}

func (x *dataStreamServiceGetTransactionStreamClient) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataStreamServiceClient) GetStreamInfo(ctx context.Context, in *StreamInfoRequest, opts ...grpc.CallOption) (*StreamInfoResponse, error) {
	out := new(StreamInfoResponse)
	err := c.cc.Invoke(ctx, "/datastream.service.v1.DataStreamService/GetStreamInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataStreamServiceServer is the server API for DataStreamService service.
// All implementations must embed UnimplementedDataStreamServiceServer
// for forward compatibility
type DataStreamServiceServer interface {
	// GetTransactionStream returns a continuous stream of transactions as they're processed
	GetTransactionStream(*TransactionStreamRequest, DataStreamService_GetTransactionStreamServer) error
	// GetStreamInfo returns information about the current datastream
	GetStreamInfo(context.Context, *StreamInfoRequest) (*StreamInfoResponse, error)
	mustEmbedUnimplementedDataStreamServiceServer()
}

// UnimplementedDataStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataStreamServiceServer struct {
}

func (UnimplementedDataStreamServiceServer) GetTransactionStream(*TransactionStreamRequest, DataStreamService_GetTransactionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTransactionStream not implemented")
}
func (UnimplementedDataStreamServiceServer) GetStreamInfo(context.Context, *StreamInfoRequest) (*StreamInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamInfo not implemented")
}
func (UnimplementedDataStreamServiceServer) mustEmbedUnimplementedDataStreamServiceServer() {}

// UnsafeDataStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataStreamServiceServer will
// result in compilation errors.
type UnsafeDataStreamServiceServer interface {
	mustEmbedUnimplementedDataStreamServiceServer()
}

func RegisterDataStreamServiceServer(s grpc.ServiceRegistrar, srv DataStreamServiceServer) {
	s.RegisterService(&DataStreamService_ServiceDesc, srv)
}

func _DataStreamService_GetTransactionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataStreamServiceServer).GetTransactionStream(m, &dataStreamServiceGetTransactionStreamServer{stream})
}

type DataStreamService_GetTransactionStreamServer interface {
	Send(*TransactionResponse) error
	grpc.ServerStream
}

type dataStreamServiceGetTransactionStreamServer struct {
	grpc.ServerStream
}

func (x *dataStreamServiceGetTransactionStreamServer) Send(m *TransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DataStreamService_GetStreamInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStreamServiceServer).GetStreamInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datastream.service.v1.DataStreamService/GetStreamInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStreamServiceServer).GetStreamInfo(ctx, req.(*StreamInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataStreamService_ServiceDesc is the grpc.ServiceDesc for DataStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datastream.service.v1.DataStreamService",
	HandlerType: (*DataStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStreamInfo",
			Handler:    _DataStreamService_GetStreamInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTransactionStream",
			Handler:       _DataStreamService_GetTransactionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "datastream_service.proto",
}
